let
    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("jVlbU9zIDv4rXVRtFVuVWQIkQM6bxxdsMjM2tgcCu3kwnobpWl+mfIGwv/5ILbfbnkuSl1RG+tzdUkufpObvv4+M06MPR9Ok5ixI3o++fwDJF5KIFEWTOnnlbKN0BugilICKGVlWviVFykk3BZ0Hv4pGEGCikKQ3Qe8GUcCiRmx4sSKpBVLDCUMtZ8fRhqciycR/fMXiqnhhRl2LuvmLBdVL/id9Z+N3aVq1gJlx2IjE1yCei4wnL5z5RdZt7eHRwpAZRdEmGYvSivNCn+wG1I5nGizkzy0cwGo5i0tm8acGRGB8DkYR9BZXWtz5s+UiNsIHFtmBERqx5y9YYDwQ5hEw6J9/2o8fzy60m+SCEjJFr3t5LgpYmFlJ8cKr/jjTM3RUWTdgBnNEpV04PUfr+EqkaAQ5SSs/gdLfNGXOm+p9V/0Z1BZsN/hUXev0EnXiVYCrrbZ51x9dSVOqpOJ1Ck6xrIDk6NC4/IExwuGgqVjxmrmW16nRoYMDTKZlUq2YyatGPAu4sGD9DvElkoLgc9xFiXZPvtAn95+fRQq+UphRhE1DBHohM8ucRXdaHm0dh3U+PKFVCRRvge4gIp/LSp+1JtzDFs5YrUQjygJ+4nIQp4R73MIlq1WTdauBlTWoJNA83QJqT/TZRMBPlGDJJklFk+CebJS55uddwCghCXWxi8JonRou8zyCXO7ZyYhId7WrM/2ZQcov+9fevlLT3cXdud0ad6AzIeLwmnmy//v7XUxQ8Vy0OZuoICHkt7F3P8gohKx+YYu2AucZBQTwmrB4tTuhivGyQDvGcWDhtZlZ2awxa5aR4Rh4hM3E4XmS0Y1ZSJeeFTOnLXgFB3DLoqy675Eux/L+NlmYNHyLXq35bhbcJZVInoAltv1jIU25YEi9Fps+pSfx+4azc0KEexFzAUxbUlpaGMEhr3kF0QMMXKYsCmI2LYuWTHAwICEuRg53MD7MEmIOqLYPgBHiyz6EXWSQOpyqgoPs7hhzbwYMG9imZ8xYtJxGXhTbC9Nmxmzm3xvwP0I7Y7SCEox5C9MIenZ2rrtDR01SrPCu0dmkwqgM5ZFqSBz2VUAtKMqGGa9QjNDRBPNoBfpxI6mzTsu2gNMDs8A14IqTsUHIYerajOdnWK5RfnZlCYbsexPNGjgEayDccz3xSX02UJdtM0CQ/rzTA083omMzF6kA03J7UdJeDLX71kQCcCKDyYjxkBtIfjWSe+w4MCMqyO6XbVVsPXQqY49qgnmLcddhMB36eHbLtsa00qXz7WTFN4Q0f4UsWY+1hv1Kb4XTeexeWw9HUa67PnAdFGwuBol/IuNHBi/s/CYZkN2f+MyyAyCXuoFbrnhCX3jK24P9SHOjNEFVVokKFtfHMl9iOZ6IYtdEzFKqHW6gkd4+ZKgaFzfsrLLE8zOvsCYoeyNKx7aGupklfUistkIi3oXtYJayO+rSTVaU+CGw8crBN8sYvUPAO8X/fel52/KNh1lhvIquwhDXjwuih5FgVvyNzZ8q5ib/YTZLKjvGVoQCy8MQAP6eEJDnuk3x7K67Sdct8C3K2THmu2vM/O5rR7JuXmayxg++7WhE/XT7hshpeTbohbybPZsMNviKPNyDZ5gp2XvfiOHBkU2gIuHxNXC+BbznyQZpSyOwBJhthVfdkytzMvGybvo64cmOidfipZCbLAsxUGJgxMkPmWd4TcfYI584Xnx/EsE/BIrHoONe3dm3HF0jsD4LRIY+7g+KtfyaUyFUFKm136Sh8tQWT/9l/gaARNFbLsFyhVm8p+eZy2DKRF4WnQBJ1VyLbMWidrMpK8qS+TlZAxPFaweUNS4p/q3aTZN2MiTXuKWIoNFk3N7PJb+W0N/XdQK9uFZcdsFobDZVuQEOk5ciZ44ec6UmMvtHusbRYKBDkvWbNXjI8i1mvPAiHS5v9errpCpEvc7lfKH0C5oBYKox8cDZiRxupOpWdqGWEQBlwFAlGt71KbdnMlWB0dq0gXYYMaS47L5gekAgBR7yxlwqzw4+MdQncQnRmlDbdTtVW6s0N6GY1pzo6RaTPFqg1qpEBi3/Cxlza/Wf6SMfL2twKLbtp3WD0HEwUEze2vpLqgi3Ti9xDYetYOhKFRvfukqHqmG03M6UJjZMZgg8eJ5DV6EmPwz3qswGDpiPyEC6lfkYhD1ioRNbxjcEKX8e6LE23JQCrlU1fcOM6PbX8NveMNiGROGuCDMdzx9XCSbgnoMjYduLGTC4w4wY7HXtgfZBdoryEvDgWvEox/E61aLwdNAJecA3aELfR4973vBs2DXpOUvBCXQuA7RbCIbYDEenQyt+kifdZEnKZW7sfEAw2T5tqybQtrDTz2yVvFNuhBcHYecfYaxXsKt9MAilPOfVyT3cZdcZh8ZgWDnsm64TCU1ti2b4Q4ZjFM+BboAWoFyMrUUOD+eGap4DZs5YaEdsvsAemjDI4ybUO0bzDa3Qx6BX1132h98UcP4zWISm+q+QsjypD/V7zI8iGgqj6a/gsukbfOD9xvqEvPmtpQmL1dp3DZgpYjuEIiyFs9/eCts1l2ervjDFZ/IOX5nRNmUOWZyyyekfLI4oWeKrTg03l8pbnWidcaRf7ia9dLr1mtArzKPt57leZcm5F1u7kVg+sVGJ0cc7/UMDHA1QB9TKa61U59kFyYmLN21V0KiNOam1snEuswzIGG2fJlD/F2WVb5t2swdnPsa2RuC9wQ/o0yGkQztmsc/m9pz5d3bIYuCymTeHVkZiZ/JM8iEQWwGLQ79cdcUgnncLzUpIZYuvoCiqOS721SZoJms3jCwjNhVPrUYG28h0B4LEHfqxy/qnWJKHSr4988eR0uz2P3Hcr6aumeSY1SFmKBkshUtk6KASWOxh9gfypa8m7Jy9d13B8uwQ5kJjzrtmZw+ONTgKnhIOOZn4S1IyLSRnxTMCfP7VQvSmsUQ6tuFKkkFnNnivWF7Km51wvdeTXuMTYa5+hvlMmC8/w1wQBrMTBn3RTfpDxCUhpocRV4TAlJVPlWLQGg/swbx1ZkHATvvWaQYJ0Ko3yKWtAJ43QUZisjnsvnaUcmbfMXr4W16PZJ3Q7YQT6IpB2Em9gZRnKO8UmI342E73c84eeKK2/DpSXQxVlHXg0k6J/RtUq5x90gE1P4QZBJ18doWJf0UPh6rtuMe772vjBJPnf7KZy2QfAP6Fya+YNJDwmDsNialfvMcJhV4L1eO7voR7rHdWKXvjPVp5nNgL7IX1gS3MgH1go6cvDX3AtLNEnTxBRECJjsCtMLyl+q8vD9EhBJqKCdINYhL9iOvJv2rY+SYr3zmXXellzaI1xAphzrYwFSnZMfSe0G6R/Y+YoA5fyQkNyKXMuWRGfM5Yl9lK9RGPmKcqO6+rEnhtJp5lm9tWfSfyKOeGJpH97+G1KA8b6MRlgsk/9XQvFo+yTbqeefLJa9KIvFtZRjQqjr5//z8=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type text) meta [Serialized.Text = true]) in type table [ComponentOfPayID = _t, ComponentOfPayDescription = _t]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ComponentOfPayID", type text}, {"ComponentOfPayDescription", type text}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"ComponentOfPayDescription", "Component of Pay Title"}, {"ComponentOfPayID", "Component of Pay ID"}})
in
    #"Renamed Columns"
